import { useState } from 'react';
import { toast } from 'sonner';
import { Building2, Plus, Search } from 'lucide-react';
import { mockTenants } from '../../data/mock';
import { Badge } from '../../components/ui/badge';
import { Button } from '../../components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../../components/ui/card';
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '../../components/ui/dialog';
import { Input } from '../../components/ui/input';
import { Label } from '../../components/ui/label';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '../../components/ui/table';

export default function CompaniesPage() {
  const [companies, setCompanies] = useState(mockTenants);
  const [search, setSearch] = useState('');
  const [open, setOpen] = useState(false);
  const visible = companies.filter((c) => c.name.toLowerCase().includes(search.toLowerCase()) || c.slug.includes(search.toLowerCase()));
  const create = (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); setCompanies((prev) => [...prev, { id: `tenant-${Date.now()}`, name: String(f.get('name')), slug: String(f.get('slug')), primaryColor: '#1e40af', active: true }]); setOpen(false); toast.success('Empresa criada com sucesso'); };
  return <div><div className="mb-7 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-sm font-semibold uppercase tracking-widest text-rose-600">Administração global</p><h1 className="text-3xl font-bold tracking-tight">Empresas</h1><p className="mt-1 text-muted-foreground">Gerencie os tenants e a operação da plataforma.</p></div><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus className="mr-2 h-4 w-4" />Nova empresa</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Criar nova empresa</DialogTitle></DialogHeader><form onSubmit={create} className="space-y-4"><div className="space-y-2"><Label>Nome da empresa</Label><Input name="name" placeholder="Ex.: Nova Distribuidora" required /></div><div className="space-y-2"><Label>Identificador</Label><Input name="slug" placeholder="nova-distribuidora" required /></div><DialogFooter><Button type="submit">Criar empresa</Button></DialogFooter></form></DialogContent></Dialog></div><div className="mb-5 grid gap-4 sm:grid-cols-3"><Card><CardContent className="flex items-center gap-3 p-5"><div className="rounded-xl bg-blue-100 p-3 text-blue-700"><Building2 className="h-5 w-5" /></div><div><p className="text-sm text-muted-foreground">Total de empresas</p><p className="text-2xl font-bold">{companies.length}</p></div></CardContent></Card><Card><CardContent className="p-5"><p className="text-sm text-muted-foreground">Ativas</p><p className="text-2xl font-bold text-emerald-600">{companies.filter((c) => c.active).length}</p></CardContent></Card><Card><CardContent className="p-5"><p className="text-sm text-muted-foreground">Inativas</p><p className="text-2xl font-bold">{companies.filter((c) => !c.active).length}</p></CardContent></Card></div><Card><CardHeader><CardTitle className="flex items-center justify-between"><span>Empresas cadastradas</span><div className="relative w-64"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input className="pl-9" placeholder="Buscar" value={search} onChange={(e) => setSearch(e.target.value)} /></div></CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Empresa</TableHead><TableHead>Identificador</TableHead><TableHead>Cor principal</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{visible.map((c) => <TableRow key={c.id}><TableCell className="font-semibold">{c.name}</TableCell><TableCell className="text-muted-foreground">{c.slug}</TableCell><TableCell><span className="mr-2 inline-block h-4 w-4 rounded-full align-middle" style={{ backgroundColor: c.primaryColor }} />{c.primaryColor}</TableCell><TableCell><Badge className={c.active ? 'bg-emerald-100 text-emerald-800' : 'bg-muted text-muted-foreground'}>{c.active ? 'Ativa' : 'Inativa'}</Badge></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div>;
}
